linters:
  enable:
    - cyclop
    - asciicheck
    - errchkjson
    - errorlint
    - gochecknoinits
    - revive
    - misspell
    - noctx
    - prealloc
    - tagliatelle
    - tenv
    - whitespace
  disable:
    - govet
