version: "3.8"
services:
  mongo:
    image: mongo:5.0.10
    container_name: "mongo"
    restart: always
    env_file:
      - local.env
    ports:
      - "27107:27107"
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: "api"
    ports:
      - "8000:8000"
    env_file:
      - local.env
